name: Release Â» 'main'

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/braviatv
          zip -r braviatv.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/braviatv/braviatv.zip
          asset_name: braviatv.zip
          tag: ${{ github.ref }}
          overwrite: true
